#!/bin/bash

#-----------
# Configurations
#-----------

DRUPAL_VERISON=${DRUPAL_VERISON-7.23}
ACCESS_CODE=${ACCESS_CODE-Kk8KLHUcoNDt3Y}
DRUPAL_ADMIN_SERVER=${DRUPAL_ADMIN_SERVER-dadmin.vm}
DRUPAL_SERVER=${DRUPAL_SERVER-apache}

APACHE_LOG_DIR=${APACHE_LOG_DIR-/var/log/apache2}

#-----------
# Install Script
#-----------

mkdir -p /var/local/apps/admin_drupal/config
mkdir -p /var/local/apps/admin_drupal/templates
mkdir -p /var/local/apps/drupal/

cp -R ./submodules/drupal/files/webapp/* /var/local/apps/admin_drupal/
chmod -R 775 /var/local/apps/admin_drupal
chmod -R 775 /var/local/apps/drupal
chmod -R 775 /var/local/apps/admin_drupal/bin

chown -R root:www-data /var/local/apps/admin_drupal
chown -R root:www-data /var/local/apps/drupal

if [[ ! -e /var/local/apps/admin_drupal/templates/default  ]]; then
  mkdir -p /var/local/apps/admin_drupal/templates/default
  (cd /var/local/apps/admin_drupal/templates/default && wget http://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERISON}.tar.gz)
  (cd /var/local/apps/admin_drupal/templates/default && tar zxfv drupal-${DRUPAL_VERISON}.tar.gz)
  mv /var/local/apps/admin_drupal/templates/default/drupal-${DRUPAL_VERISON} /var/local/apps/admin_drupal/templates/default/drupal
fi

sed -i s/@ACCESS_CODE@/${ACCESS_CODE}/g /var/apps/admin_drupal/app/models/AccessCode.php
cp ./submodules/drupal/files/admin_${DRUPAL_SERVER}_conf /etc/${DRUPAL_SERVER}/sites-enabled/admin_drupal
printf '#!/bin/bash\ntouch /tmp/${DRUPAL_SERVER}_reload\nchmod 777 /tmp/${DRUPAL_SERVER}_reload\n/var/apps/admin_drupal/bin/touchandgo /tmp/${DRUPAL_SERVER}_reload /var/apps/admin_drupal/bin/${DRUPAL_SERVER}_reload &' > /var/apps/${DRUPAL_SERVER}/startup.d/touchandgo_${DRUPAL_SERVER}_reload
chmod 755 /var/apps/${DRUPAL_SERVER}/startup.d/touchandgo_${DRUPAL_SERVER}_reload
sed -i s/@DRUPAL_ADMIN_SERVER@/$DRUPAL_ADMIN_SERVER/g /etc/${DRUPAL_SERVER}/sites-enabled/admin_drupal
