#!/bin/bash

#-----------
# Configurations
#-----------

DRUPAL_VERISON=${DRUPAL_VERISON-7.23}
ACCESS_CODE=${ACCESS_CODE-Kk8KLHUcoNDt3Y}

#-----------
# Install Script
#-----------

mkdir -p /var/apps/admin_drupal/

cp -R ./submodules/drupal/files/webapp/* /var/apps/admin_drupal/
chmod -R 755 /var/apps/admin_drupal/bin/*

if [[ ! -e /var/apps/admin_drupal/config/drupal  ]]; then
  (cd /var/apps/admin_drupal/config && wget http://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERISON}.tar.gz)
  (cd /var/apps/admin_drupal/config && tar zxfv drupal-${DRUPAL_VERISON}.tar.gz)
  mv /var/apps/admin_drupal/config/drupal-${DRUPAL_VERISON} /var/apps/admin_drupal/config/drupal
fi

sed -i s/@ACCESS_CODE@/$ACCESS_CODE/g /var/apps/admin_drupal/app/models/AccessCode.php

if [[ ! -e /etc/nginx/sites-enabled/admin_drupal ]]; then
  cp ./submodules/drupal/files/admin_nginx_conf /etc/nginx/sites-enabled/admin_drupal
fi
