#!/bin/bash

#-----------
# Configurations
#-----------

DRUPAL_VERISON=${DRUPAL_VERISON-7.23}
ACCESS_CODE=${ACCESS_CODE-Kk8KLHUcoNDt3Y}
DRUPAL_ADMIN_SERVER=${DRUPAL_ADMIN_SERVER-dadmin.vm}


#-----------
# Install Script
#-----------

mkdir -p /var/apps/admin_drupal/
mkdir -p /var/apps/drupal/

cp -R ./submodules/drupal/files/webapp/* /var/apps/admin_drupal/
chmod -R 775 /var/apps/admin_drupal
chmod -R 775 /var/apps/drupal
chmod -R 775 /var/apps/admin_drupal/bin

chown -R root:www-data /var/apps/admin_drupal
chown -R root:www-data /var/apps/drupal


if [[ ! -e /var/apps/admin_drupal/config/drupal  ]]; then
  (cd /var/apps/admin_drupal/config && wget http://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERISON}.tar.gz)
  (cd /var/apps/admin_drupal/config && tar zxfv drupal-${DRUPAL_VERISON}.tar.gz)
  mv /var/apps/admin_drupal/config/drupal-${DRUPAL_VERISON} /var/apps/admin_drupal/config/drupal
fi

sed -i s/@ACCESS_CODE@/$ACCESS_CODE/g /var/apps/admin_drupal/app/models/AccessCode.php

cp ./submodules/drupal/files/admin_nginx_conf /etc/nginx/sites-enabled/admin_drupal
sed -i s/@DRUPAL_ADMIN_SERVER@/$DRUPAL_ADMIN_SERVER/g /etc/nginx/sites-enabled/admin_drupal

printf '#!/bin/bash\ntouch /tmp/nginx_reload\nchmod 777 /tmp/nginx_reload\n/var/apps/admin_drupal/bin/touchandgo /tmp/nginx_reload /var/apps/admin_drupal/bin/nginx_reload &' > /var/apps/nginx/startup.d/touchandgo_nginx_reload
chmod 755 /var/apps/nginx/startup.d/touchandgo_nginx_reload
