#!/bin/bash
FROM_DIR=$1
DRUPAL_NAME=$2
TO_DIR=/var/apps/$DRUPAL_NAME

mkdir -p ${TO_DIR}

cp -R ${FROM_DIR}/* ${TO_DIR}/
cp ${TO_DIR}/sites/default/default.settings.php ${TO_DIR}/sites/default/settings.php
chmod a+w ${TO_DIR}/sites/default/settings.php
chmod a+w ${TO_DIR}/sites/default

mkdir -p /etc/nginx/sites-enabled
cp /var/apps/drupal_admin/drupal_nginx_conf /etc/nginx/sites-enabled/${DRUPAL_NAME}
sed -i "s|@DRUPAL_ROOT@|$TO_DIR|g" /etc/nginx/sites-enabled/${DRUPAL_NAME}
